server {
    listen 80;
    server_name apto.egogc.com;

    root /usr/share/nginx/html;
    index apto.html;

    location / {
        try_files /apto.html =404;
    }
}

server {
    listen 80 default_server;

    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }
}
